/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE data-typeBaseService PLEASE EDIT ../data-type.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { DataType } from '../../domain/datastructure_db/data-type';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../DataType.service.ts
 */

/*
 * SCHEMA DB DataType
 *
	{
		Lenght: {
			type: 'Number'
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		DataType: {
			type: Schema.ObjectId,
			ref : "DataEntity"
		},
	}
 *
 */
@Injectable()
export class DataTypeBaseService {

    contextUrl: string = environment.endpoint + '/datatype';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * DataTypeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: DataType): Observable<DataType> {
        return this.http
            .post<DataType>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * DataTypeService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DataTypeService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<DataType> {
        return this.http
            .get<DataType>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DataTypeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<DataType[]> {
        return this.http
            .get<DataType[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * DataTypeService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: DataType): Observable<DataType> {
        return this.http
            .post<DataType>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
