/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE data-entityBaseService PLEASE EDIT ../data-entity.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { DataEntity } from '../../domain/datastructure_db/data-entity';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../DataEntity.service.ts
 */

/*
 * SCHEMA DB DataEntity
 *
	{
		Index: {
			type: 'Boolean'
		},
		Name: {
			type: 'String',
			required : true
		},
		Nullable: {
			type: 'Boolean',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		DataEntity: [{
			type: Schema.ObjectId,
			ref : "DataObject"
		}],
		DataType: {
			type: Schema.ObjectId,
			ref : "DataEntity"
		},
		ValidationRule: [{
			type: Schema.ObjectId,
			ref : "DataEntity"
		}],
	}
 *
 */
@Injectable()
export class DataEntityBaseService {

    contextUrl: string = environment.endpoint + '/dataentity';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * DataEntityService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: DataEntity): Observable<DataEntity> {
        return this.http
            .post<DataEntity>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * DataEntityService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DataEntityService.findByDataType
    *   @description CRUD ACTION findByDataType
    *   @param Objectid key Id of model to search for
    *
    */
    findByDataType(id: string): Observable<DataEntity[]> {
        return this.http
            .get<DataEntity[]>(this.contextUrl + '/findByDataType/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * DataEntityService.findByValidationRule
    *   @description CRUD ACTION findByValidationRule
    *   @param Objectid key Id of model to search for
    *
    */
    findByValidationRule(id: string): Observable<DataEntity[]> {
        return this.http
            .get<DataEntity[]>(this.contextUrl + '/findByValidationRule/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * DataEntityService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<DataEntity> {
        return this.http
            .get<DataEntity>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * DataEntityService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<DataEntity[]> {
        return this.http
            .get<DataEntity[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * DataEntityService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: DataEntity): Observable<DataEntity> {
        return this.http
            .post<DataEntity>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
